changesetBaseRefs:
  - develop
  - origin/develop
  - master
  - origin/master
  - main
  - origin/main

nodeLinker: node-modules

plugins:
  - checksum: 26e8fe1580b68848fd4498cd646f44a38bfee77658c4678777003ff5ff01977e4113cf01a3809aa2727a46aa5342d2afe8dbe610800da3b6850f74af7d0ab1fa
    path: .yarn/plugins/@yarnpkg/plugin-changelog.cjs
    spec: 'https://raw.githubusercontent.com/furystack/furystack/refs/heads/develop/packages/yarn-plugin-changelog/bundles/%40yarnpkg/plugin-changelog.js'

yarnPath: .yarn/releases/yarn-4.12.0.cjs
